apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-node-port-service
  namespace: airflow
spec:
  type: NodePort
  selector:
    component: webserver
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
