executor: LocalExecutor

workers:
  persistence:
    size: 32Gi

scheduler:
  # Mount additional volumes into scheduler.
  extraVolumes:
    - name: airflow-dag-volume
      hostPath: 
        path: "{{CURRENT_DIRECTORY}}/src/dags"
        type: Directory
  extraVolumeMounts:
    - name: airflow-dag-volume
      mountPath: /opt/airflow/dags
